### ISSUE TITLE
ObservedGeneration should only be set if Status is fully updated

### ISSUE THREAD

**Issue by grantr** [knative/pkg#1226]
## Expected Behavior
_Followup from [this thread in Slack #serving-api](https://knative.slack.com/archives/CA4DNJ9A4/p1586958789227800)_

If ObservedGeneration == Generation, I expect that the object's Status reflects the actual status of the resource.

## Actual Behavior
If the reconcile is written to return errors early, then the Status may not be fully accurate.

Example from @mattmoor:
```go
foo.Status.ObsGen = foo.Gen
if bar, err := reconcileFoo(); err != nil {
  // What happens here?
  return err
} if bar.Something() {
  bar.Status.MarkSomething()
}
foo.Status.MarkReady()
return nil
```

If the reconciler returns on line 4, then the statuses of the `Something` and `Ready` conditions actually reflect the previous generation's status, not the current generation.

## Additional Info
One solution mentioned in the thread is to re-initialize status to fully unknown at the beginning of every reconcile so that no information is carried over from the previous generation. This works for non-timestamped status fields like `address`, but is suboptimal for conditions as it would make `lastTransitionTime` inaccurate.

Instead of replacing each condition, we could mark existing conditions before reconcile and unmark them when updated during reconcile. After the reconcile, any conditions that are still marked are set to unknown. This preserves the functionality of `lastTransitionTime`.

@dprotaso @markusthoemmes @mattmoor @vaikas

**Comment by mattmoor** [comment]
> One solution mentioned in the thread is to re-initialize status to fully unknown at the beginning of every reconcile so that no information is carried over from the previous generation. This works for non-timestamped status fields like address, but is suboptimal for conditions as it would make lastTransitionTime inaccurate.

This isn't entirely accurate.  The proposal in the thread was scoped to `conditions`, and `lastTransitionTime`'s use of `apis.VolatileTime` combined with how we guard status updates is specifically designed to avoid timestamp churn.

A while back I actually tried to do this and uncovered a few places in Serving that have a pretty hard dependency on the imperative use of Status as state, so I gave up, but I like the suggestion @vaikas made that we not have a bad default behavior because of a few bad apples.

To avoid back-compat issues, I'd propose that we introduce `ResetConditions()` to force all of a resources conditions to Unknown, and shift all of our controllers (that can) over to this model.

**Comment by whaught** [comment]
I tried to take a stab at this issue with PR #1261

The idea here is that rather than reset all conditions, we include logic in gen-reconciler to bump observed generation. If we've bumped generation with an error and detect that the readiness status is unchanged, we move it to unknown with a warning.

This avoids the need to reset all conditions and might be a little more easily backwards compatible. It's using a new tag for generation so we can migrate reconcilers to it one-by-one to ensure it functions properly.

**Comment by whaught** [comment]
/close

I'm closing this issue - the work should be finished in /pkg to allow for this new behavior. I will be referencing issue https://github.com/knative/serving/issues/4937 as I ensure /serving is using the new behavior and I've opened https://github.com/knative/eventing/issues/3099 to begin implementation for eventing
