### ISSUE TITLE
Move leaderelection away from enableComponents

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#1319]
/area API
/kind cleanup

In hindsight, this was a poor choice for how to enable leaderelection, since it doesn't follow our paradigm of supporting hot reloads.

A few problems top-of-mind:
 - Enabling it for components doesn't restart the components (this leads to fragile trickery like scaling down/up deployments to force restarts after patching the configmap).
 - The field validation for this hinders our extensibility (e.g. imagine validating the component names within `knative-sources` 😬)

cc @mgencur @pmorie

**Comment by mattmoor** [comment]
I'm thinking that a flag defined by `sharedmain` would solve things, but wondering what others think.

**Comment by mgencur** [comment]
How would the user enable/disable leader election with the flag? By editing the controller's Deployment and changing the `args` section?
I'm thinking that it's not necessary to give the user options for enabling/disabling each controller (autoscaler, autoscaler-hpa, controller, etc.) separately. Having an option for setting this for `all` components that we support seems sufficient to me.
The ConfigMap `config-leaderelection` seems a natural place for me to have these settings. I believe it's possible to enforce pod restarts when this config is changed, something like this??:
```
logger.Info("Leader-elected mode changed. Restarting controller...)
os.Exit(1)
```
There are more configuration options for leader election, not just enabling/disabling it. Right now I think none of them can be changed at runtime because we don't "watch" the ConfigMap. So we'd need  more flags to be able to configure this? Or we'd need the flag and also the ConfigMap.

**Comment by mgencur** [comment]
OTOH, having leader election enabled by default with only one pod for the given deployment would be an option too. With just one pod it doesn't have effect so this could be safe. I can try a test PR with this to let all test suites run.

**Comment by mattmoor** [comment]
> having leader election enabled by default with only one pod for the given deployment would be an option too.

IMO we should move the currently supported components to this model, but we need a way for components that don't yet support it (e.g. autoscaler) to be able to opt-out.

**Comment by pmorie** [comment]
I agree the current implementation isn't optimal - a CLI flag sounds okay to me.

**Comment by mattmoor** [comment]
This is done

**Comment by mgencur** [comment]
OK. This is closed without even looking at the code in the linked PR? Sigh.
