### ISSUE TITLE
Check dependant CRDs are installed before start controllers

### ISSUE THREAD

**Issue by cathyzhyi** [knative/pkg#1663]
## Expected Behavior
When starting up the controller, if any dependant CRDs are missing, print error message to the user and exit gracefully.

## Actual Behavior
When starting up the controller, with CRDs missing, the program can get stuck in an infinite loop with error message `the server could not find the requested resource` while the pod STATUS still shows running.

## Steps to Reproduce the Problem

1. Installing Knative eventing without applying `https://github.com/knative/eventing/blob/master/config/300-subscription.yaml`

**Comment by cathyzhyi** [comment]
@adamharwayne has proposed a potential fix under discussion https://github.com/Harwayne/knative-eventing/pull/51

**Comment by mattmoor** [comment]
The intent of the current design is to enable folks to repackage things pretty easily downstream, so that controllers can be combined or split relatively easily for different downstream "shrink wrapping".

That said, we pretty fundamentally expect types and rbac to exist for the set of controllers/informers linked into a particular controller process.  What happens if someone installs subscription later?  what happens if someone deletes subscription later?  What happens when the subscription CRD (or its RBAC) are simply applied in the wrong order?  Feels like there are a set of analogous problems in the webhook as well.

Generally our approach thus far has been that there is a fair amount of coupling between the set of things linked in a controller and the set of CRDs available in the cluster, and that optional CRDs should be linked to optional controller processes.

**Comment by mattmoor** [comment]
Could you elaborate at all on what you are trying to do and why, so that we understand the constraints you are trying to solve for a bit better?

**Comment by cathyzhyi** [comment]
> Could you elaborate at all on what you are trying to do and why, so that we understand the constraints you are trying to solve for a bit better?

So the original issue we had is https://github.com/google/knative-gcp/issues/1468 when installing knative-gcp customer should install both serving and eventing for now. We would like to give the customer a clear error message if one of them is missing.  Take eventing for example, we decided we can check if `broker` or `trigger` exist in order to tell if eventing is properly installed and if those CRDs are missing we can give customer an error msg and not start.

**Comment by cathyzhyi** [comment]
> Could you elaborate at all on what you are trying to do and why, so that we understand the constraints you are trying to solve for a bit better?

Hey @mattmoor, hope https://github.com/knative/pkg/issues/1663#issuecomment-683999949 answers your question. Do you think it justifies the change or there might be a better way to achieve what we want to do? Thanks!

**Comment by mattmoor** [comment]
I'd really rather make install-time considerations like this an Operator concern than forcing each component to validate the cluster state at startup.
