### ISSUE TITLE
Gracefully apply multiple PodSpec Bindings to a single subject resource

### ISSUE THREAD

**Issue by scothis** [knative/pkg#1786]
## Expected Behavior

When multiple PodSpec-able Bindings target the same subject resource, each binding should be applied by the webhook when the subject is created/updated.

## Actual Behavior

Only one of the Bindings is applied to the subject via the webhook. The other Bindings are applied via the controller. While the subject will reach a level state, there is unnecessary churn. For example, extra Revisions are created for a subject Configuration. Depending on what other controllers are in the system, there could be a reconciliation cycle thrashing the API Server.

## Additional Info

Refs https://github.com/vmware-labs/service-bindings/issues/78

**Comment by n3wscott** [comment]
Note the `Undo` method will also be destructive.

**Comment by scothis** [comment]
> Note the `Undo` method will also be destructive.

`Undo` isn't inherently destructive, it depends on what's being undone.

**Comment by glyn** [comment]
Clarification of intended behaviour:

1. For a given subject, if some Bindings match exactly and others inexactly, should they all be applied to the subject? Or should the presence of an exact match cause inexact matches to be ignored?

2. For a given subject, if no Bindings match exactly and more than one Binding matches inexactly, should all the inexactly matching Bindings be applied to the subject? (The answer seems obvious, but I want to be certain since it's a change from the current behaviour.)

3. What should happen when more than one Binding targets the same subject, but the Bindings' `Do` methods make incompatible changes (such as setting an env var to distinct values)?

Clarification of current behaviour:

1. Is there an implicit precondition on a Binding's `Do` method that the changes it wants to make must not already be present in the subject? If not, `Undo` could corrupt the subject instead of undoing the effects of `Do` (i.e. not changing the subject).

**Comment by scothis** [comment]
Good questions @glyn 

> 1. For a given subject, if some Bindings match exactly and others inexactly, should they all be applied to the subject? Or should the presence of an exact match cause inexact matches to be ignored?
>
> 2. For a given subject, if no Bindings match exactly and more than one Binding matches inexactly, should all the inexactly matching Bindings be applied to the subject? (The answer seems obvious, but I want to be certain since it's a change from the current behaviour.)

Every binding referencing the subject should be applied. So all exact matches **and** all inexact matches. This is the current behavior of the controller, the webhook's behavior should match.

> 3. What should happen when more than one Binding targets the same subject, but the Bindings' Do methods make incompatible changes (such as setting an env var to distinct values)?
>
> 4. Is there an implicit precondition on a Binding's Do method that the changes it wants to make must not already be present in the subject? If not, Undo could corrupt the subject instead of undoing the effects of Do (i.e. not changing the subject).

The output may be invalid. Since this behavior already exists in the controller, a poorly written binding is still poorly written when applied via the webhook. (Consistently poor in this case)

A common practice is to call Undo immediately with the Do method. It's the responsibility of the binding implementation to make sure that undoing a single binding doesn't break other existing bindings. If there is common state, it needs to be coordinated by the implementation. The ServiceBinding implementation, for example, takes care to Do/Undo incrementally.
