### ISSUE TITLE
More than one defaulting webhook controller won't work in the same binary with HA enabled

### ISSUE THREAD

**Issue by yanweiguo** [knative/pkg#1979]
## Expected Behavior
I can set more than one [defaulting webhook controller](https://github.com/knative/pkg/blob/master/webhook/resourcesemantics/defaulting/controller.go#L39) in the same binary with leader election (HA) enabled. Same for configmaps and validation webhook.

## Actual Behavior
If more than one defaulting webhook controllers are set in the same binary with leader election (HA) enabled, only one of the controllers would reconcile as expected.

## Steps to Reproduce the Problem

1. In knative serving webhook [main.go](https://github.com/knative/serving/blob/master/cmd/webhook/main.go#L78), set up another `defaulting.NewAdmissionController` for Istio [MutatingWebhookConfiguration](https://github.com/knative-sandbox/net-istio/blob/master/config/500-mutating-webhook.yaml)
2. Deploy knative serving and the Istio MutatingWebhookConfiguration.
3. Check Istio MutatingWebhookConfiguration and the serving [MutatingWebhookConfiguration](https://github.com/knative/serving/blob/master/config/core/webhooks/defaulting.yaml), you will fine that only one of them gets reconciled.

## Additional Info
This is because for defaulting webhook controllers, they share the same lease. The lease name is `defaultingwebhook`: https://github.com/knative/pkg/blob/master/webhook/resourcesemantics/defaulting/controller.go#L77. However when setting up leader election, each controller uses different resource lock ID: https://github.com/knative/pkg/blob/master/leaderelection/context.go#L114. So only one of them will actually got set up successfully.

In Knative serving autoscaler, KPA controller and metrics controller share the same lease as well. But they have the same resource lock ID: https://github.com/knative/serving/blob/master/cmd/autoscaler/main.go#L269. The callbacks of those two controllers will be triggered when starting leading the lease.

**Comment by yanweiguo** [comment]
Maybe the simplest way to fix is to use the name of MutatingWebhookConfiguration for the names of reconcile queue and the lease as well, which is a parameter of [defaulting.NewAdmissionController](https://github.com/knative/pkg/blob/master/webhook/resourcesemantics/defaulting/controller.go#L39). Same for validation and configmaps webhook controllers.

cc @mattmoor

**Comment by mattmoor** [comment]
> set up another defaulting.NewAdmissionController for Istio

Don't do that. 😜 

In mink I'm running a defaulting webhook for all of serving, eventing, and tekton as a single endpoint (I used to run a lot more!).  Pass all the types to a single defaulting webhook.


Is there a legitimate reason to be running multiple defaulting webhooks vs. a single with all the types...?

**Comment by yanweiguo** [comment]
> Is there a legitimate reason to be running multiple defaulting webhooks vs. a single with all the types...?

I don't see one. Currently in our downstream branch we just copy both the MutatingWebhookConfiguration in serving repo and net-istio repo. I guess it is for easy sync with upstream.

If using single defaulting webhook is the right way to go, I'll do that. Thanks.

**Comment by mattmoor** [comment]
Yeah, that's the way things were intended to work: https://github.com/mattmoor/mink/blob/f6f4dc092ce14818642cacf87ce26ac892d5a392/cmd/webhook/defaulting.go#L57

LMK if you need any pointers / help.

**Comment by yanweiguo** [comment]
It turned out that https://github.com/knative-sandbox/net-istio/blob/master/config/500-mutating-webhook.yaml has a matchExpression while https://github.com/knative/serving/blob/master/config/core/webhooks/defaulting.yaml doesn't. Can't simply merge them.

**Comment by Cynocracy** [comment]
Is 'the webhook may not be running on cluster but needs to negotiate with other clusters for ownership' a good reason?

In an advanced case where the user does not want their on-cluster control plane availability to be tied to their own data plane, I could see having multiple webhooks (some with different failure domains) that would all need to negotiate.

**Comment by yanweiguo** [comment]
Talked with @mattmoor in slack, there are a few solutions:

1. Make multiple defaulting webhooks work with HA. Defaulting webhook is not designed to support multiple instances. However I'm not sure why (we didn't talk about it). @mattmoor could you explain?
2. Add the filtering logic in https://github.com/knative-sandbox/net-istio/blob/master/pkg/defaults/deployment_defaults.go#L60 instead of depending on matchExpression. But it will become control plane of all deployments, including knative deployments.
3. Implement a new webhook controller like the defaulting webhook and use it for those MutatingWebhookConfiguration who have the same matchExpression.
4. Change the defaulting webhooks to support multiple `admissionReviewVersions`. Is it doable?

**Comment by dprotaso** [comment]
### General observations/context I have:

1) Kubernetes lets you have [_multiple_ webhook entries](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1/) in the validating/mutating resource
   1) Our webhook tooling only supports a single webhook entry per resource 
   1) There's not explanation why i) is the way it is since it's been like this forever (initial serving commit)
1) @markusthoemmes's recent PR https://github.com/knative/pkg/pull/1949 preserves webhook properties that we don't set (ie. object selectors)
1) Two webhook controllers of the same class (ie. defaulting, validation, config, cert, psbinding) can't co-exist because they compete for the same lease.
   1) Controllers don't have this problem because they generally have unique names (component + work queue)
1) We also have a bug where _after_ the CRDs are created but _before_ the webhook computes/applies rules invalid resources can be created

### Comments on the Solutions: 

> Make multiple defaulting webhooks work with HA. Defaulting webhook is not designed to support multiple instances. However I'm not sure why (we didn't talk about it). @mattmoor could you explain?

I interpret this as there should only be a single registered webhook that uses `apis.Defaultable` to default a type.

> Add the filtering logic in https://github.com/knative-sandbox/net-istio/blob/master/pkg/defaults/deployment_defaults.go#L60 instead of depending on matchExpression. But it will become control plane of all deployments, including knative deployments

I'm not a fan of this - is the goal to avoid deploying two webhook?

> Implement a new webhook controller like the defaulting webhook and use it for those MutatingWebhookConfiguration who have the same matchExpression.

I sorta mentioned this here: https://github.com/knative/pkg/issues/1140#issuecomment-598850652
This could work with multiple webhook registrations per resource. With Markus's change certain selectors won't be reconciled away.

Related to my third point should we continue to have this inconsistency between webhooks and controllers. This would imply that you need to compose webhooks like matt does here: https://github.com/knative/pkg/issues/1979#issuecomment-755526782 vs the traditional way of composing controllers 

> 4. Change the defaulting webhooks to support multiple admissionReviewVersions. Is it doable?

Not sure what you mean - these admission versions are just the webhook envelope between the k8s api server <=> webhook. They're currently v1 & v1beta1
