### ISSUE TITLE
Should our default log output be specific to stackdriver?

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#2187]
@dprotaso I still see some references to the `stackdriver` name like here: https://github.com/knative/pkg/blob/952ee7db67049390a6a1067657370b711400d433/logging/config.go#L58
Shouldn't we remove it from the whole codebase? There are more from a quick search, detected via the IDE.

_Originally posted by @skonto in https://github.com/knative/pkg/issues/2183#issuecomment-878343583_

**Comment by evankanderson** [comment]
For logging, we're using https://github.com/blendle/zapdriver for configuration of `zap`, I think.

This has the following implications:

* There are a [couple logging levels that get enriched](https://github.com/blendle/zapdriver#pre-configured-stackdriver-optimized-encoder), and renames the `timestamp` field from `ts`, also `severity` and `message`.
* Special logging for [TraceContext](https://github.com/blendle/zapdriver#tracecontext) and [HTTP requests](https://github.com/blendle/zapdriver#http)
* Additional detail beyond the Zap defaults for error reporting, which includes `filePath`, `lineNumber`, and `functionName`.

I don't have a strong feeling here; the extra exported fields seem handy to me, but if naming fields `timestamp` instead of `ts` causes other compatibility issues, I could be convinced to switch to a different standard. (I think the last discussion was "what standards are there for this?"; "not sure, Stackdriver is documented here"; "I can't easily find others with a web search, let's go for it")

This is still producing JSON-format logs; it's augmenting the JSON field data and possibly renaming some fields.

**Comment by evankanderson** [comment]
(Which is different than adding Stackdriver gRPCs clients to every binary)
