### ISSUE TITLE
How to use injection-gen to generate code

### ISSUE THREAD

**Issue by fhuzero** [knative/pkg#2225]
/kind question

I am trying to to generate _pkg/client/injection/kube/client/client.go_ using _pkg/codegen/cmd/injection-gen/main.go_ since in  _client.go_ it says `// Code generated by injection-gen. DO NOT EDIT.` But I got error "versioned clientset package cannot be empty " when building _main.go_. I would be appreciated if anyone could help me !

**Comment by Yiyiyimu** [comment]
ref: https://github.com/knative/pkg/issues/2200#issuecomment-903209657

**Comment by odacremolbap** [comment]
Might this be because you need to generate the clientset, listers and informers prior to generating the injection for all elements?

The order should be:

- k8s.io/code-generator/cmd/client-gen
- k8s.io/code-generator/cmd/lister-gen (needs generated client)
- k8s.io/code-generator/cmd/informer-gen (needs generated client and listers)
- knative.dev/pkg/codegen/cmd/injection-gen (needs generated client, listers and informers)

**Comment by fhuzero** [comment]
Thank you for providing the order! @odacremolbap
