### ISSUE TITLE
Disable controllers using a flag

### ISSUE THREAD

**Issue by pierDipi** [knative/pkg#2338]
I would like to disable controllers using a command-line flag

## Proposal

- Add a `disable-controllers` flag that is a comma-separated list of controller names.
- Add [1] to main.go

[1]:

```golang
// MainNamed runs the generic main flow for controllers and webhooks.
func MainNamed(ctx context.Context, component string, ctors ...injection.NamedControllerConstructor) {

	disabledControllers := flag.String("disable-controllers", "", "Comma-separated list of disabled controllers.")

	// HACK: This parses flags, so the above should be set once this runs.
	cfg := injection.ParseAndGetRESTConfigOrDie()

	enabledCtors := enabledControllers(strings.Split(*disabledControllers, ","), ctors)

	MainWithConfig(ctx, component, cfg, enabledCtors...)
}
```

where `NamedControllerConstructor` is

```golang
// NamedControllerConstructor is a ControllerConstructor with an associated name.
type NamedControllerConstructor struct {
	// Name is the name of associated with the controller returned by ControllerConstructor.
	Name string
	// ControllerConstructor is a constructor for a controller.
	ControllerConstructor ControllerConstructor
}
```

**Comment by odacremolbap** [comment]
what is the scenario behind this flag?

I can picture a controller binary being deployed where some objects are not going to be used and some cycles can be saved by disabling some of the controllers, or maybe someone implementing their own version of one of the controllers.

On the saving cycles scenario if I'm not wrong, the informers for any disabled controller would still be loaded because of the `init` functions imported, but yet, not adding handlers would probably save some cycles.

**Comment by pierDipi** [comment]
The use case is to disable controllers in order to safely rollout competing controllers (reconciling the same resource).
