### ISSUE TITLE
Webhook UserInfo adds the incorrect annotation

### ISSUE THREAD

**Issue by dgerd** [knative/pkg#511]
## Expected Behavior

Knative Serving applies an UpdaterAnnotation of:

`UpdaterAnnotation = GroupName + "/lastModifier"`

## Actual Behavior

Knative pkg applies an Updater Annotation of:

`UpdaterAnnotationSuffix = "/updater"`

The difference here prevents Knative Serving from migrating to use the pkg version of the user info. As this was recently added in pkg and likely has no dependencies on the string yet I would like to change this to `/lastModifier`.

## Additional Info

https://github.com/knative/pkg/blob/master/webhook/user_info.go#L34
https://github.com/knative/serving/blob/master/pkg/apis/serving/register.go#L61

cc @aliok @mattmoor

**Comment by vagababov** [comment]
+1
I think this was raised during the codereview.

**Comment by dgerd** [comment]
It looks like eventing used "lastModifier" as well before it was migrated to pkg

https://github.com/knative/eventing/blob/2b8f8cd64e9b4a1d32e77b0147c760ef9a2330cd/pkg/apis/eventing/register.go

**Comment by aliok** [comment]
as @vagababov said, this was discussed here: https://github.com/knative/pkg/pull/467#pullrequestreview-251389165

I changed it to `/lastModifier` in knative/pkg first but because it is a breaking change, I reverted it to `/updater` there as suggested.

But now that you pointed that both uses `lastModifier`, we should change this to that in knative/pkg as well.
