### ISSUE TITLE
Mako-stub logs interrupted abruptly

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/pkg#728]
## Expected Behavior
Write all points published to mako to the stdout of the container

## Actual Behavior
After a bit the container is closed and the output is truncated, without writing all output lines

## Steps to Reproduce the Problem

Run a benchmark in eventing with a long duration configuration (e.g. more than 300 seconds) and then pipe the mako stub logs to a file **from the container creation**. You'll see that at some point the log is abruptly terminated and not all results are written.

## Additional Info
My hypothesis is that the mako-stub doesn't wait for stdout to be completely flushed before exit 

## Alternative proposal
We could refactor the stub to expose an http server that expects one single http request and replies with all metrics. When the response is complete, the mako-stub exits. 

/area test-and-release
/kind bug

**Comment by grantr** [comment]
I looked into whether stdout needs to be synced on exit. Apparently trying to sync stdout on linux returns `EINVAL` because stdout can't be synced: https://github.com/uber-go/zap/issues/328#issuecomment-284337436.

The stub code calls https://golang.org/pkg/encoding/csv/#Writer.Flush which should take care of flushing the csv buffers to stdout. If the container is exiting before that call occurs, that could cause some rows to be missing from the output.

Does the log always print complete rows, or does it print partial rows?
Is there any indication of the exit status of the pod?

**Comment by slinkydeveloper** [comment]
@grantr 
> Does the log always print complete rows, or does it print partial rows?
It prints partial rows sometimes

> Is there any indication of the exit status of the pod?
Success exit status (0)

**Comment by slinkydeveloper** [comment]
Closed by https://github.com/knative/pkg/pull/868 . Now for big logs devs should use the http mode of the stub and collect results with the provided script
